# Generated by Django 2.1 on 2019-04-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_len', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_len', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
