export const GET_IRIS_DATA = "GET_IRIS_DATA";
export const CLEAR_IRIS_DATA = 'CLEAR_IRIS_DATA';
export const DELETE_ONE_IRIS = "DELETE_ONE_IRIS";
export const SET_EDIT_IRIS = "SET_EDIT_IRIS";
export const SET_EDIT_IRIS_CLUSTER = "SET_EDIT_IRIS_CLUSTER";
export const UPDATE_ONE_IRIS = "UPDATE_ONE_IRIS";
export const ADD_ONE_IRIS = "ADD_ONE_IRIS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

